### PR TITLE
Added a delnotifs command to delete notifications

### PR DESCRIPTION
**Pull request by raiderrobert**

### CODE REVIEW

**Comment by jproffitt** [comment]
@raiderrobert do you think it would be better to name the command something more obvious? Django hardly ever abbreviates names like that. Just look at all of the build in management commands:

    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

So how about something like `clearnotifications` or `deletenotifications`?

**Comment by raiderrobert** [comment]
@jproffitt it just seemed so long, given that you can also hand over arguments

**Comment by jproffitt** [comment]
Ok. Thanks for adding it!

**Comment by georgmzimmer** [comment]
how about a test of the parameters?

**Pull request merged**
